name: Deploy

on:
  push:
    branch:
      - main

concurrency: deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        run: |
          echo "188.120.230.133 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK7gL3O9UrX6EJ/fDVqB5wlh7e25OxdPlWkIHkNtAdf8" >> ~/.ssh/known_hosts
          docker context create --docker "host=ssh://root@188.120.230.133" --description "deploy server" "mfabt.club"
          docker --context "mfabt.club" compose up --build -d
